// <auto-generated />
namespace LawyersAdda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v23));
        
        string IMigrationMetadata.Id
        {
            get { return "201512230315297_v23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
